// Type stub for the wasm-pack output at engine/pkg/wasim_engine.
// The real declarations are generated by wasm-pack; this covers the shape we use.
declare module '@engine/wasim_engine' {
  export class WasmEngine {
    constructor(model_json: string)
    model_json(): string
    model_summary(): string
    run_json(config_json: string): string
    sensitivity_json(spec_json: string): string
    set_constant(id: string, value: number): void
    set_rv_param(id: string, param_name: string, value: number): void
    topo_order_json(): string
    free(): void
  }
  /** Validate a candidate model without a persistent engine (authoring reconcile loop).
   *  Returns JSON `{ ok, errors, warnings, topo }`; never throws. */
  export function validate_json(model_json: string): string
  export default function init(): Promise<void>
}
